stages:
  - build
  - deploy

variables:
  SECURE_FILES_DOWNLOAD_PATH: ./config

.before_script: &before_script
  before_script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp ${SECURE_FILES_DOWNLOAD_PATH}/google-services-debug.json app/src/debug/google-services.json
    - cp ${SECURE_FILES_DOWNLOAD_PATH}/google-services-release.json app/src/release/google-services.json

build-debug:
    stage: build
    image: fabernovel/android:api-34-v1.8.0
    before_script:
        - *before_script
    script:
        - ./gradlew :app:assembleDebug
        - mv app/build/outputs/apk/debug/*.apk app/build/outputs/apk/debug/app-debug.apk
    artifacts:
        paths:
            - app/build/outputs/apk/debug/app-debug.apk

build-release:
    stage: build
    image: fabernovel/android:api-34-v1.8.0
    before_script:
        - *before_script
    script:
        - ./gradlew :app:assembleRelease
        - mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/app-release.apk
    artifacts:
        paths:
            - app/build/outputs/apk/release/app-release.apk

upload:
    stage: deploy
    needs:
        - job: build-debug
          artifacts: true
        - job: build-release
          artifacts: true
    script:
      - |
        curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" -L --upload-file app/build/outputs/apk/debug/app-debug.apk "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/debug/2fas/app-debug.apk" && \
        curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" -L --upload-file app/build/outputs/apk/release/app-release.apk "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/release/2fas/app-release.apk"